### ISSUE TITLE
SyntaxError: "1" contains no units

### ISSUE THREAD

**Issue by San-WierPa** [SciCatProject/scicat-backend-next#362]
### Summary
While using the scicat-backend image, 
+ I'm attempting to upload metadata of datasets to scicat, which is running in a docker-compose environment
+ The application was functioning as expected until the pasted error started to occur during every dataset-upload attempt via the web interface and via local execution of a python-script
+ The error message indicates a syntax issue with a numerical value containing units
+ No changes were made to the application configuration or codebase prior to the error occurring.

Error:
```shell
scicat_1           | SyntaxError: "1" contains no units
scicat_1           |     at Function.Unit.parse (/home/node/app/node_modules/mathjs/lib/cjs/type/unit/Unit.js:447:13)
scicat_1           |     at new Unit (/home/node/app/node_modules/mathjs/lib/cjs/type/unit/Unit.js:87:20)
scicat_1           |     at Function.numberBigNumberFractionComplexString (/home/node/app/node_modules/mathjs/lib/cjs/type/unit/function/unit.js:56:14)
scicat_1           |     at unit (/home/node/app/node_modules/typed-function/typed-function.js:1085:85)
scicat_1           |     at convertToSI (/home/node/app/dist/common/utils.js:11:44)
scicat_1           |     at /home/node/app/dist/common/utils.js:39:65
scicat_1           |     at Array.forEach (<anonymous>)
scicat_1           |     at appendSIUnitToPhysicalQuantity (/home/node/app/dist/common/utils.js:22:25)
scicat_1           |     at /home/node/app/dist/common/utils.js:44:129
scicat_1           |     at Array.forEach (<anonymous>)
scicat_1           |     at appendSIUnitToPhysicalQuantity (/home/node/app/dist/common/utils.js:22:25)
scicat_1           |     at FormatPhysicalQuantitiesInterceptor.intercept (/home/node/app/dist/common/interceptors/format-physical-quantities.interceptor.js:24:60)
scicat_1           |     at /home/node/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
scicat_1           |     at Object.handle (/home/node/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:21:61)
scicat_1           |     at UTCTimeInterceptor.intercept (/home/node/app/dist/common/interceptors/utc-time.interceptor.js:23:21)
scicat_1           |     at /home/node/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
scicat_1           | SyntaxError: "1" contains no units
scicat_1           |     at Function.Unit.parse (/home/node/app/node_modules/mathjs/lib/cjs/type/unit/Unit.js:447:13)
scicat_1           |     at new Unit (/home/node/app/node_modules/mathjs/lib/cjs/type/unit/Unit.js:87:20)
scicat_1           |     at Function.numberBigNumberFractionComplexString (/home/node/app/node_modules/mathjs/lib/cjs/type/unit/function/unit.js:56:14)
scicat_1           |     at unit (/home/node/app/node_modules/typed-function/typed-function.js:1085:85)
scicat_1           |     at convertToSI (/home/node/app/dist/common/utils.js:11:44)
scicat_1           |     at /home/node/app/dist/common/utils.js:39:65
scicat_1           |     at Array.forEach (<anonymous>)
scicat_1           |     at appendSIUnitToPhysicalQuantity (/home/node/app/dist/common/utils.js:22:25)
scicat_1           |     at /home/node/app/dist/common/utils.js:44:129
scicat_1           |     at Array.forEach (<anonymous>)
scicat_1           |     at appendSIUnitToPhysicalQuantity (/home/node/app/dist/common/utils.js:22:25)
scicat_1           |     at FormatPhysicalQuantitiesInterceptor.intercept (/home/node/app/dist/common/interceptors/format-physical-quantities.interceptor.js:24:60)
scicat_1           |     at /home/node/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
scicat_1           |     at Object.handle (/home/node/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:21:61)
scicat_1           |     at UTCTimeInterceptor.intercept (/home/node/app/dist/common/interceptors/utc-time.interceptor.js:23:21)
scicat_1           |     at /home/node/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
```

### Current Behaviour
+ Output in terminal and mongo-express entries indicate that all works
+ But nothing is displayed on the webserver

### Expected Behaviour
+ e.g. execute python-script to upload dataset and display it on the webserver.
+ Output in terminal and mongo-express show successful creation of dataset

### Extra Details
It appears that the error is originating from the mathjs library, which is used to perform mathematical operations involving units of measurement. The error message indicates that the code is attempting to parse a unit of measurement from a string that has a value of 1, but it is unable to do so.
I have tried using different images to resolve the error, but the issue persists.
I suspect the error may be caused by changes to the scicat codebase or dependencies, but cannot determine the exact cause.

I am unsure whether this error is caused by a change in any JSON object or if it is being caused by an issue on the server-side. Can someone please help me identify the root cause of this error and provide a solution?

**Comment by nitrosx** [comment]
@San-WierPa will you be able to provide an example of the data that you are trying to ingest and triggers the error?
Which library are you using in python to ingest the data?
Thanks

**Comment by San-WierPa** [comment]
Thank you for your reply. I'm using an openapi generated client and the same payload. Both did not change through the last month (and I did docker-compose down/up a few times since the last change of the payload). Just yesterday morning, I was still able to upload one dataset and then it just "stopped" (except that I can still see the whole JSON object, while accessing mongo-express). Anyway, here is the payload:

```python
 {
            "owner_group": "University of Wuppertal",  #TODO
            "access_groups": "NO_THUMBNAIL", #TODO
            "creation_location": "wuppertal", #TODO
            "principal_investigator": "someone", #TODO
            "dataset_name": titlename
            + " "
            + datetime.now().strftime("%Y-%m-%d-%H_%M_%S"),
            "type": "raw", #TODO
            "is_published": False, #TODO
            "creation_time": str(datetime.now().isoformat()),
            "source_folder": "None",
            "owner": "None", #TODO
            "contact_email": "a@b.de", #TODO
            "scientific_metadata": {
                "Abstract": "This is a very descriptive and long informative abstract to understand this dataset a bit better!", #TODO
                "Source": "LABORATORY", #TODO
                "Mode": "ABSORPTION", #TODO
                "RAW": {
                    "edge_step": {
                        "value": 0.0,
                        "unit": "1",
                        "documentation": "height of the detected edge step",
                    },
                    "k_max": {
                        "value": 0.0,
                        "unit": "1/angstrom",
                        "documentation": "considered angular wavenumber",
                    },
                    "noise": {
                        "value": 0.0,
                        "unit": "1",
                        "documentation": "noise of the measurement",
                    },
                    "energy_resolution": {
                        "value": 0.0,
                        "unit": "eV",
                        "documentation": "energy resolution of the measured spectrum in eV",
                    },
                },
                "PROCESSED": {
                    "amplitude_reduction_factor": {
                        "Z_ranges": {
                            "tentoforty": {
                                "value": 0.0,
                            },
                            "fortytoeighty": {
                                "value": 0.0,
                            },
                        },
                        "unit": "1",
                        "documentation": "amplitude factor from the processed spectrum",
                    }
                },
                "Figures": {
                    "data": None,
                    "k": None,
                    "R": None,
                },
            },
        }
```

**Comment by nitrosx** [comment]
@San-WierPa the issue might be that the unit is set to 1.
Is there a reason why you have the following?
```
"unit": "1"
```
What is the meaning of it?

As a test: can you try to ingest the same payload where you remove completely __"unit" : "1"__?
