### ISSUE TITLE
proposal ingestion: incorrect validation

### ISSUE THREAD

**Issue by bpedersen2** [SciCatProject/scicat-backend-next#495]
If I try to ingest a sample proposal (swagger ui with proposal ingestor token) I get either a validation error (400) or a server error (500) with mutually exclusive failures:

with  creates/updated fields for `MeasurementPeriodList`
```
{
  "proposalId": "0000",
  "pi_email": "pedersen@frm2.tum.de",
  "pi_firstname": "Bjoern",
  "pi_lastname": "Pedersen",
  "email": "pedersen@frm2.tum.de",
  "firstname": "string",
  "lastname": "string",
  "title": "test proposal",
  "abstract": "string",
  "startTime": "2023-05-15T13:48:08.499Z",
  "endTime": "2023-05-15T13:48:08.499Z",
  "MeasurementPeriodList": [
    {
      "createdBy": "xxx",
      "updatedBy": "xxx",
      "createdAt": "2023-05-15T13:48:08.499Z",
      "updatedAt": "2023-05-15T13:48:08.499Z",
      "instrument": "string",
      "start": "2023-05-15T13:48:08.499Z",
      "end": "2023-05-15T13:48:08.499Z",
      "comment": "string"
    }
  ],
  "ownerGroup": "scicat",
  "accessGroups": [
    "domuser"
  ],
  "instrumentGroup": "string"
}
```

=>
```
{
  "statusCode": 400,
  "message": [
    "MeasurementPeriodList.0.property createdBy should not exist",
    "MeasurementPeriodList.0.property updatedBy should not exist",
    "MeasurementPeriodList.0.property createdAt should not exist",
    "MeasurementPeriodList.0.property updatedAt should not exist"
  ],
  "error": "Bad Request"
}
```

Without these fields:
```
{
  "proposalId": "0000",
  "pi_email": "pedersen@frm2.tum.de",
  "pi_firstname": "Bjoern",
  "pi_lastname": "Pedersen",
  "email": "pedersen@frm2.tum.de",
  "firstname": "string",
  "lastname": "string",
  "title": "test proposal",
  "abstract": "string",
  "startTime": "2023-05-15T13:48:08.499Z",
  "endTime": "2023-05-15T13:48:08.499Z",
  "MeasurementPeriodList": [
    {

      "instrument": "string",
      "start": "2023-05-15T13:48:08.499Z",
      "end": "2023-05-15T13:48:08.499Z",
      "comment": "string"
    }
  ],
  "ownerGroup": "scicat",
  "accessGroups": [
    "domuser"
  ],
  "instrumentGroup": "string"
}
```

=>
```
[Nest] 1  - 05/15/2023, 1:58:53 PM   ERROR [ExceptionsHandler] ProposalClass validation failed: MeasurementPeriodList.0.updatedBy: Path `updatedBy` is required., MeasurementPeriodList.0.createdBy: Path `createdBy` is required.
2023-05-15T15:58:53.816125467+02:00 ValidationError: ProposalClass validation failed: MeasurementPeriodList.0.updatedBy: Path `updatedBy` is required., MeasurementPeriodList.0.createdBy: Path `createdBy` is required.
2023-05-15T15:58:53.816142399+02:00     at model.Document.invalidate (/home/node/app/node_modules/mongoose/lib/document.js:3125:32)
2023-05-15T15:58:53.816147768+02:00     at EmbeddedDocument.Subdocument.invalidate (/home/node/app/node_modules/mongoose/lib/types/subdocument.js:225:12)
2023-05-15T15:58:53.816152561+02:00     at /home/node/app/node_modules/mongoose/lib/document.js:2913:17
2023-05-15T15:58:53.816158147+02:00     at /home/node/app/node_modules/mongoose/lib/schematype.js:1349:9
2023-05-15T15:58:53.816162703+02:00     at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by bpedersen2** [comment]
I guess the correct solution would be to make the fields non-required ( as they should be auto-filled)
