### ISSUE TITLE
ERROR [ExceptionsHandler] Proposal validation failed: MeasurementPeriodList: Cast to Embedded failed for value

### ISSUE THREAD

**Issue by nguyenlinhlinh** [SciCatProject/scicat-backend-next#77]
## Issue Name
ERROR [ExceptionsHandler] Proposal validation failed: MeasurementPeriodList: Cast to Embedded failed for value
### Summary
I have a test case where it tries to add a new proposal the data looks like bellow. 
```
{
  proposalId: '20170251',
  pi_email: 'Firstname.LastName@gmail.com',
  pi_firstname: 'Firstname',
  pi_lastname: 'Lastname',
  email: 'Firstname.LastName@gmail.com',
  firstname: 'Firstname',
  lastname: 'Lastname',
  title: 'TEST for checking data handling',
  abstract: 'In-house proposal for IT to test data handling\r\n',
  startTime: null,
  endTime: null,
  ownerGroup: '20170251-group',
  accessGroups: [ 'biomax' ],
  createdBy: 'anonymous',
  updatedBy: 'ingestor',
  MeasurementPeriodList: [
    {
      instrument: 'Mirror',
      start: '2020-12-21T14:48:59.272+01:00',
      end: '2020-12-21T14:48:59.272+01:00',
      comment: 'Good',
      createdAt: '2021-05-26T07:41:30.838Z',
      createdBy: 'anonymous',
      updatedBy: 'ingestor'
    }
  ],
  createdAt: '2020-12-23T13:38:08.074Z',
  updatedAt: '2022-03-24T11:37:24.200Z'
}
```
The backend throws error likes bellow
```
[Nest] 7944  - 05/20/2022, 11:04:10 AM   ERROR [ExceptionsHandler] Proposal validation failed: MeasurementPeriodList: Cast to Embedded failed for value "[
  {
    instrument: 'Mirror',
    start: '2020-12-21T14:48:59.272+01:00',
    end: '2020-12-21T14:48:59.272+01:00',
    comment: 'Good',
    createdAt: '2021-05-26T07:41:30.838Z',
    createdBy: 'anonymous',
    updatedBy: 'ingestor'
  }
]" (type Array) at path "MeasurementPeriodList"
ValidationError: Proposal validation failed: MeasurementPeriodList: Cast to Embedded failed for value "[
  {
    instrument: 'Mirror',
    start: '2020-12-21T14:48:59.272+01:00',
    end: '2020-12-21T14:48:59.272+01:00',
    comment: 'Good',
    createdAt: '2021-05-26T07:41:30.838Z',
    createdBy: 'anonymous',
    updatedBy: 'ingestor'
  }
]" (type Array) at path "MeasurementPeriodList"
    at model.Document.invalidate (/Users/linhnguyen/Documents/scicat/scicat-backend-next/node_modules/mongoose/lib/document.js:2969:32)
    at model.$set (/Users/linhnguyen/Documents/scicat/scicat-backend-next/node_modules/mongoose/lib/document.js:1450:12)
    at model.$set (/Users/linhnguyen/Documents/scicat/scicat-backend-next/node_modules/mongoose/lib/document.js:1137:16)
    at model.Document (/Users/linhnguyen/Documents/scicat/scicat-backend-next/node_modules/mongoose/lib/document.js:161:12)
    at model.Model (/Users/linhnguyen/Documents/scicat/scicat-backend-next/node_modules/mongoose/lib/model.js:115:12)
    at new model (/Users/linhnguyen/Documents/scicat/scicat-backend-next/node_modules/mongoose/lib/model.js:4827:15)
    at ProposalsService.create (/Users/linhnguyen/Documents/scicat/scicat-backend-next/src/proposals/proposals.service.ts:26:33)
    at ProposalsController.create (/Users/linhnguyen/Documents/scicat/scicat-backend-next/src/proposals/proposals.controller.ts:43:38)
    at /Users/linhnguyen/Documents/scicat/scicat-backend-next/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
### Steps to Reproduce
- Send a post request to `/proposals` with proposal data like above
### Current Behaviour
- Backend throws error and user get http code 500
### Expected Behaviour
- A new proposal is added to db

**Comment by henrikjohansson712** [comment]
The ingestor account should not be able to add proposals, but the proposalIngestor account should be.

**Comment by nguyenlinhlinh** [comment]
Ah ok because our current consumer uses ingestor account to add new proposal so I thought it should be the same but maybe it has changed over time.

**Comment by henrikjohansson712** [comment]
Could it be failing because the measurement period is missing an `updatedAt` field?

**Comment by nguyenlinhlinh** [comment]
I tried with updateAt but still got the same error.
